[package]
name = "aoc-2025"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
dialoguer = "0.12.0"
inventory = "0.3.21"
itertools = "0.14.0"
lazy_static = "1.5.0"
regex = "1.12.2"
